# ==== Stage 1: сборка ====
FROM node:18-alpine AS builder
WORKDIR /app

# копируем манифесты и tsconfig
COPY package*.json tsconfig*.json ./

# ставим все зависимости (включая dev)
RUN npm install

# копируем исходники и билдим весь проект
COPY . .
RUN npm run build

# ==== Stage 2: production-образ ====
FROM node:18-alpine
WORKDIR /app

# ставим только prod-зависимости и гасим хуск
COPY package*.json ./
RUN npm ci --omit=dev --ignore-scripts

# копируем готовый JS
COPY --from=builder /app/dist ./dist

# выставляем порт (3001/3004/3002/3003)
EXPOSE 3000

# и запускаем нужный сервис

CMD ["node", "dist/microservices/main.js"]