FROM node:18

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig*.json ./

# Install dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

# Install dependencies
RUN npm install

COPY . .

RUN npm run build

EXPOSE 3002

CMD ["node", "dist/main"] 